[build]
  publish = "."

[[headers]]
  for = "/*"
    [headers.values]
    Basic-Auth = ":${PASSWORD}"
    X-Debug-Info = "Netlify config processed"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true